assemblies:
  Aberdeen_Man
  Amsterdam_Leid
  Amsterdam_Wee
  B
  Birmingham_Maria
  Cardiff_Maria
  co-1
  co-2
  co-3
  co-4
  co-5
  co-6
  co-7
  co-8
  co-9
  co-B
  Dundee_Clat
  Dundee_Maria
  DW-TW
  DW-TWABC
  Edinburgh_Glen
  Effluent
  Exeter_Maria
  Glasgow_Bal
  Glasgow_Mil
  GS
  GX
  HB
  HK
  HLJ
  HN
  London_Maria
  LY
  Nieuwkoop_DHB
  OCW
  POE
  QD
  S41-73
  SG
  SH
  South_Holland_Dla
  Spannenburg
  SRR6797127
  SRR6797128
  SRR6797129
  SRR6797130
  SRR6797131
  SRR6797132
  SRR6797133
  SRR6797134
  SRR6797135
  SRR6797136
  SRR6797137
  SRR6797138
  SRR6797139
  SRR6797140
  SRR6797141
  SRR6797142
  SRR6797143
  SRR6797144
  SRR6797145
  SRR6797146
  SRR6797147
  SRR6797148
  SRR6797149
  SRR6797150
  SRR6797151
  SX
  TB
  W
  WC